import { test, expect, devices } from '@playwright/test';
test.use({
  ...devices['Pixel 2'],
});
test('test', async ({ page }) => {
    test.setTimeout(12000000);
  await page.goto('http://172.27.22.216:8001/login');
  await page.goto('http://172.27.22.216:8001/login#login');
  await page.locator('text=Email Password Show Forgot Password? >> [placeholder="jane\\@example\\.com"]').click();
  await page.locator('text=Email Password Show Forgot Password? >> [placeholder="jane\\@example\\.com"]').fill('Administrator');
  await page.locator('text=Email Password Show Forgot Password? >> [placeholder="jane\\@example\\.com"]').press('Tab');
  await page.locator('[placeholder="•••••"]').fill('admin');
  await Promise.all([
    page.waitForNavigation(/*{ url: 'http://172.27.22.216:8001/app' }*/),
    page.locator('[placeholder="•••••"]').press('Enter')
  ]);
  await page.locator('text=Home Create Workspace Edit Actions >> svg').nth(1).click();
  await page.locator('text=HR').click();
  await expect(page).toHaveURL('http://172.27.22.216:8001/app/hr');
  await page.locator('text=Designation').click();
  await expect(page).toHaveURL('http://172.27.22.216:8001/app/designation');
  await page.locator('button:has-text("Add Designation")').click();
  await page.locator('text=Designation undefined >> input[type="text"]').fill('Data analyst');
  await page.locator('button:has-text("Save")').click();
  await page.locator('button:has-text("Add Designation")').click();
  await page.locator('text=Designation undefined >> input[type="text"]').fill('Data auditer');
  await page.locator('text=Save').nth(3).click();
  await page.locator('button:has-text("Add Designation")').click();
  await page.locator('text=Designation undefined >> input[type="text"]').fill('Data entrier');
  await page.locator('text=Save').nth(4).click();
  await page.locator('button:has-text("Add Designation")').click();
  await page.locator('text=Designation undefined >> input[type="text"]').fill('Data visualizer');
  await page.locator('button:has-text("Save")').nth(3).click();
  await page.locator('button:has-text("Add Designation")').click();
  await page.locator('text=Designation undefined >> input[type="text"]').fill('Coach');
  await page.locator('button:has-text("Save")').nth(4).click();
  await page.locator('button:has-text("Add Designation")').click();
  await page.locator('text=Designation undefined >> input[type="text"]').fill('Head researcher');
  await page.locator('text=New Designation Designation Head researcher Edit in full page Save >> button').nth(4).click();
  await page.locator('button:has-text("Add Designation")').click();
  await page.locator('text=Designation undefined >> input[type="text"]').fill('Salesman');
  await page.locator('text=New Designation Designation Salesman Edit in full page Save >> button').nth(4).click();
  await page.locator('button:has-text("Add Designation")').click();
  await page.locator('text=Designation undefined >> input[type="text"]').fill('Sales executive');
  await page.locator('text=New Designation Designation Sales executive Edit in full page Save >> button').nth(4).click();
  await page.locator('button:has-text("Add Designation")').click();
  await page.locator('text=Designation undefined >> input[type="text"]').fill('video editor');
  await page.locator('text=New Designation Designation video editor Edit in full page Save >> button').nth(4).click();
  await page.locator('button:has-text("Add Designation")').click();
  await page.locator('text=Designation undefined >> input[type="text"]').fill('graphic designer');
  await page.locator('text=New Designation Designation graphic designer Edit in full page Save >> button').nth(4).click();
  await page.locator('button:has-text("Add Designation")').click();
  await page.locator('text=Designation undefined >> input[type="text"]').fill('graphikar');
  await page.locator('text=New Designation Designation graphikar Edit in full page Save >> button').nth(4).click();
  await page.locator('button:has-text("Add Designation")').click();
  await page.locator('text=Designation undefined >> input[type="text"]').fill('councelor');
  await page.locator('text=New Designation Designation councelor Edit in full page Save >> button').nth(4).click();
  await page.locator('button:has-text("Add Designation")').click();
  await page.locator('text=Designation undefined >> input[type="text"]').fill('HTML');
  await page.locator('text=New Designation Designation HTML Edit in full page Save >> button').nth(4).click();
  await page.locator('button:has-text("Add Designation")').click();
  await page.locator('text=Designation undefined >> input[type="text"]').fill('css');
  await page.locator('text=New Designation Designation css Edit in full page Save >> button').nth(4).click();
  await page.locator('button:has-text("Add Designation")').click();
  await page.locator('text=Designation undefined >> input[type="text"]').fill('full stack');
  await page.locator('text=New Designation Designation full stack Edit in full page Save >> button').nth(4).click();
  await page.locator('button:has-text("Add Designation")').click();
  await page.locator('text=Designation undefined >> input[type="text"]').fill('choreographer');
  await page.locator('text=New Designation Designation choreographer Edit in full page Save >> button').nth(4).click();
});
